[build]
  functions = 'functions'
  command = 'yarn build'
  publish = 'dist'


[[redirects]]
  from = '/*'
  to = '/'
  status = 200

[dev]
  command='yarn start'
  port=8888
  targetPort=3000
  publish='dist'
